# Generated by Django 4.2 on 2026-01-18 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0028_adminpremiumsettings_auto_renew_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov miqdori")),
                ('payment_method', models.CharField(choices=[('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd pul'), ('other', 'Boshqa')], max_length=20, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Ishlov berilmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Amalga oshmadi'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Tranzaksiya ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank nomi')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hisob raqami')),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hisob egasi')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="To'lov isboti")),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_approve_after_payment',
            field=models.BooleanField(default=False, verbose_name="To'lovdan keyin avtomatik tasdiqlash"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_account_number',
            field=models.CharField(default='8600 1234 5678 9012', max_length=100, verbose_name='Bank hisob raqami'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_name',
            field=models.CharField(default='Xalq Banki', max_length=100, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_recipient_name',
            field=models.CharField(default='Tez Sot MChJ', max_length=200, verbose_name='Hisob egasi nomi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_amount_per_day',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name="Kunlik to'lov miqdori (so'm)"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_amount_per_product',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name="Mahsulot uchun to'lov miqdori (so'm)"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_required',
            field=models.BooleanField(default=True, verbose_name="Premium uchun to'lov talab qilinadimi"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='require_payment_proof',
            field=models.BooleanField(default=True, verbose_name="To'lov isbotini talab qilish"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="To'lov haqida xabar yuborish uchun", max_length=200, null=True, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='telegram_channel_id',
            field=models.CharField(blank=True, help_text="To'lov xabarlari yuboriladigan kanal", max_length=100, null=True, verbose_name='Telegram Channel ID'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="To'lov miqdori"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd pul'), ('other', 'Boshqa')], default='bank_transfer', max_length=50, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/requests/', verbose_name="To'lov isboti (chek rasmi)"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_required',
            field=models.BooleanField(default=True, verbose_name="To'lov talab qilinadimi"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('paid', "To'langan"), ('confirmed', 'Tasdiqlangan'), ('failed', "To'lov amalga oshmadi")], default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="To'lov miqdori"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd pul'), ('other', 'Boshqa')], default='bank_transfer', max_length=50, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="To'lov isboti (chek rasmi)"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_required',
            field=models.BooleanField(default=True, verbose_name="To'lov talab qilinadimi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('paid', "To'langan"), ('confirmed', 'Tasdiqlangan'), ('failed', "To'lov amalga oshmadi")], default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_fee_amount',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name="Premium to'lov miqdori (eski)"),
        ),
        migrations.AlterField(
            model_name='premiumnotification',
            name='notification_type',
            field=models.CharField(choices=[('expiry_soon', 'Premium muddati tugash arafasida'), ('expired', 'Premium muddati tugadi'), ('new_request', "Yangi premium so'rovi"), ('admin_action', 'Admin harakati'), ('product_limit', 'Mahsulot limiti tugab qoldi'), ('auto_renewed', 'Premium avtomatik uzaytirildi'), ('payment_submitted', "To'lov yuborildi"), ('payment_confirmed', "To'lov tasdiqlandi"), ('payment_required', "To'lov talab qilinadi")], max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('payment_pending', "To'lov kutilmoqda"), ('payment_confirmed', "To'lov tasdiqlandi")], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('active', 'Faol'), ('payment_pending', "To'lov kutilmoqda"), ('payment_confirmed', "To'lov tasdiqlandi")], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['payment_status'], name='fronend_pre_payment_263ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['payment_status'], name='fronend_pre_payment_e169a8_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin'),
        ),
        migrations.AddField(
            model_name='payment',
            name='premium_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fronend.premiumrequest', verbose_name="Premium so'rovi"),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='fronend_pay_transac_cd6b69_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='fronend_pay_user_id_034dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='fronend_pay_status_84d259_idx'),
        ),
    ]
