# Generated by Django 4.2 on 2026-01-18 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0029_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='daily_payment_explanation',
            field=models.TextField(blank=True, help_text="To'lov haqida tushuntirish matni", null=True, verbose_name="Kunlik to'lov tushuntirishi"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='enable_auto_extend',
            field=models.BooleanField(default=True, help_text="Agar yoqilsa, mavjud premiumga yangi muddat qo'shiladi", verbose_name="Avtomatik muddat qo'shish"),
        ),
        migrations.CreateModel(
            name='PremiumTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('new', 'Yangi premium'), ('extend', 'Premium uzaytirish'), ('renew', 'Premium qayta sotib olish'), ('product_add', "Premium mahsulot qo'shish"), ('manual', "Admin tomonidan qo'lda")], max_length=20, verbose_name='Tranzaksiya turi')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Miqdor')),
                ('days_added', models.PositiveIntegerField(default=0, verbose_name="Qo'shilgan kunlar")),
                ('old_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Oldingi tugash sanasi')),
                ('new_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Yangi tugash sanasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin izohlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fronend.payment', verbose_name="To'lov")),
                ('premium_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fronend.premiumrequest', verbose_name="Premium so'rovi")),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Amalga oshirgan admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Premium Tranzaksiya',
                'verbose_name_plural': 'Premium Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='premiumtransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='fronend_pre_user_id_f042b8_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumtransaction',
            index=models.Index(fields=['created_at'], name='fronend_pre_created_6c4928_idx'),
        ),
    ]
